// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOKUdGLQ2J0rzymH1gZDSFLT0Jv1WIj_A',
    appId: '1:18427902073:android:4ebfd104d7e91b7333fca8',
    messagingSenderId: '18427902073',
    projectId: 'tong-6b5fd',
    storageBucket: 'tong-6b5fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOKUdGLQ2J0rzymH1gZDSFLT0Jv1WIj_A',
    appId:
        '1:18427902073:ios:your-ios-app-id', // You'll need to add iOS app in Firebase Console
    messagingSenderId: '18427902073',
    projectId: 'tong-6b5fd',
    storageBucket: 'tong-6b5fd.firebasestorage.app',
    iosBundleId: 'com.example.tong',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOKUdGLQ2J0rzymH1gZDSFLT0Jv1WIj_A',
    appId:
        '1:18427902073:web:your-web-app-id', // You'll need to add Web app in Firebase Console
    messagingSenderId: '18427902073',
    projectId: 'tong-6b5fd',
    storageBucket: 'tong-6b5fd.firebasestorage.app',
  );
}
